<?php
session_start();
if(empty($_SESSION['id']) || empty($_SESSION['pwd'])){
?>
<script>
window.location.assign('login.php');
</script>
<?php
}
$con = mysqli_connect($_SERVER['SERVER_ADDR'],'root','','BLOG');
if(!$_SESSION['loggedin']){
?>
<script>
window.location.assign('login.php');
</script>
<?php
}
else
{
?>
<html lang="en">
<head>

<title>FAQ&nbsp; -&nbsp;CenturyLink Cloud</title>

<meta name='description' content='Backed by its industry-leading cloud platform, Tier 3 is the enterprise cloud for your business-critical applications.' />
<link rel='canonical' href='http://www.centurylinkcloud.com/faq' />
<!-- generated by seo_lite -->

	<meta charset="UTF-8" />
  <link href="assets/img/site/favicon.ico" rel="shortcut icon" type="image/x-icon">
	<!-- CSS -->
	<link rel="stylesheet" href="assets/css/bootstrap.css" />
	<link rel="stylesheet" href="assets/css/site.css" />
	<!-- JS -->
        <script src="assets/js/modernizr.js"></script>
	<script src="assets/js/jquery-1.8.3.min.js"></script>
	<script src="assets/js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="https://use.typekit.net/ytc4emj.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>


<script type="application/javascript">var _prum={id:"51672ea8e6e53d624e000001"};var PRUM_EPISODES=PRUM_EPISODES||{};PRUM_EPISODES.q=[];PRUM_EPISODES.mark=function(b,a){PRUM_EPISODES.q.push(["mark",b,a||new Date().getTime()])};PRUM_EPISODES.measure=function(b,a,b){PRUM_EPISODES.q.push(["measure",b,a,b||new Date().getTime()])};PRUM_EPISODES.done=function(a){PRUM_EPISODES.q.push(["done",a])};PRUM_EPISODES.mark("firstbyte");(function(){var b=document.getElementsByTagName("script")[0];var a=document.createElement("script");a.type="text/javascript";a.async=true;a.charset="UTF-8";a.src="//rum-static.pingdom.net/prum.min.js";b.parentNode.insertBefore(a,b)})();</script>

<style>
.header {
	height: 60px;
}
</style>
</head>
<body data-spy="scroll" data-target="#sidebar" data-offset="140" id="scrollpane" >
<!-- Google Tag Manager -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PP4JT9"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PP4JT9');</script>
<!-- End Google Tag Manager -->
<?php
print file_get_contents("header");
?>
<!-- /header -->
<div class="body full-page resources">
		<div class="container">
	    <div class="row">

          <div class="span12">
          <h1>Welcome to Electronics Club's Blog!</h1>
          </div>
        </div>
				<div class="row">
        <div class="span2">
            <div id="sidebar" class="anchor-sidebar"  data-spy="affix" data-offset-top="140" data-offset-bottom="420">

	<ul class="side nav nav-pills nav-stacked">
<?php
	$db = "SELECT * FROM Topics";
	$res = mysqli_query($con,$db);
	while($row = mysqli_fetch_array($res)){
		echo '<li><a href="blog.php#'.$row['TableName'].'">'.$row['Topic'].'</a></li>';
	}
?>
	<li ><a href="blog.php#NewTopic" style="color:red;">Start a new discussion</a></li>

	
</ul>
</div>  
        </div>
        <div class="span9 offset1">
        
<?php
	$res = mysqli_query($con,$db);
	while($row = mysqli_fetch_array($res)){
		echo '<section id="'.$row['TableName'].'" name="'.$row['TableName'].'">';
		echo '
		<div class="row">
			<div class="span3">
        		<h2>'.$row['Topic'].'</h2>
      		</div>
      		<div class="span6">
      		';
      	$result = mysqli_query($con,"SELECT * FROM ".$row['TableName']);
      	while($newrow = mysqli_fetch_array($result)){
      		echo '
      		<h5>'.$newrow["Data"].'</h5>
      		<p>posted by '.$newrow['Author'].' on '.$newrow['Time'].'</p>
      			';
      	}
      	echo '
      		<button onclick="'.$row['TableName'].'Toggle()">
      			<script>
					function '.$row['TableName'].'Toggle(){
  					document.getElementById("TA'.$row['TableName'].'").style.display="inline";
				}
				</script>
      			Add opinion
      		</button>
      		<div id="TA'.$row['TableName'].'" style="display:none;"> 
      		<form method="post" action="updateblog.php">
      			<textarea autofocus required rows="3" name="TA'.$row['TableName'].'"></textarea><br>
      			<input type="text" style="display:none;" name="topicname" value="'.$row['TableName'].'">
      			<input type="submit">
      		</form>
      		</div>
      		';
      	echo '
      	</div>
      	</div>
      	</section>
      		';
	}
?>

		<section id="NewTopic">
  		  <div class="row">
      		<div class="span3">
        		<h2>New Discussion</h2>
      		</div>
      		<div class="span6">
        	<form action="blognewtopic.php" method="post">
        	<textarea required name="topicname"placeholder="Discussion Name"></textarea><br>
        	<input type="submit" value="Create Topic"/>
        	</form>
      </div>
    </div>
  </section>                
 </div>

    </div>
	</div>
</div>


<!-- /footer -->
<!-- JS -->
<script src="assets/js/bootstrap-transition.js"></script>
<script src="assets/js/bootstrap-alert.js"></script>
<script src="assets/js/bootstrap-modal.js"></script>
<script src="assets/js/bootstrap-dropdown.js"></script>
<script src="assets/js/bootstrap-tooltip.js"></script>
<script src="assets/js/bootstrap-popover.js"></script>
<script src="assets/js/bootstrap-button.js"></script>
<script src="assets/js/bootstrap-carousel.js"></script>

<script src="assets/js/twitter-bootstrap-hover-dropdown.min.js"></script>
<script src="assets/js/bootstrap-affix.js"></script>
<script src="assets/js/jquery.scrollTo-1.4.3.1-min.js"></script>
<script src="assets/js/bootstrap-scrollspy.js"></script>
<script src="assets/js/bootstrap-tab"></script>
<script>
$('[data-spy="scroll"]').each(function () {
  var $spy = $(this).scrollspy('refresh')
});
</script>
<script src="assets/js/froogaloop2.min.js"></script>
<script src="assets/js/jquery.offsets.js"></script>
<script src="assets/js/modalVideo.js"></script>




<style type="text/css">
.lpPoweredBy {display:none;}
#lpChatSales,#lpChatSupport{position:fixed;left:0;top:250px;z-index:100;width:38px;height:157px;cursor:pointer;}.lpPoweredBy{display:none;}#lpChatSales tbody{border-top:none;}#lpChatSales tr.lpStaticButtonTR{background:transparent;border-top:none;border-bottom:none;}#lpChatSales tr.lpStaticButtonTR td{padding:0;}

</style>


<script type="text/javascript">
	document.write(unescape("%3Cscript src='" + document.location.protocol +  "//munchkin.marketo.net/munchkin.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script>Munchkin.init('978-XFN-673');</script>
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0001/2219.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>
<?php
}
?>